#!/bin/bash

##### Troubleshooting #####
# Requires docker and the image prepared by yaqwsx:  https://github.com/yaqwsx/KiKit
# Run this command from within the PCB project directory (this file must be located in the same directory)
# docker run -it -v "$(pwd):/kikit" yaqwsx/kikit kikit/makePanel

##### Troubleshooting #####
# Line endings must be LF (not CRLF)

# M.Ruppe - Core Electronics


# Panelise a 25.4mm square PCB in the 'standard panel'
now=$(date +"%Y-%m-%d")

kikit panelize grid \
--space 2.5 \
--gridsize 6 10 \
--tabwidth 12 \
--htabs 0 \
--vcuts \
--radius 1 \
--railsTb 10.025 \
--fiducials 12.5 7.5 1.5 3 \
--tooling 5 5 3 \
kikit/PiicoDev-Distance-Sensor-VL53L1X.kicad_pcb \
"kikit/P104 v10 $now".kicad_pcb
